// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Expense struct {
	ID          uuid.UUID
	Description sql.NullString
	Amount      string
	Split       json.RawMessage
	Status      string
	SettledBy   uuid.NullUUID
	CreatedBy   uuid.NullUUID
	Payee       json.RawMessage
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type ExpenseMapping struct {
	ExpenseID uuid.UUID
	GroupID   uuid.NullUUID
	UserID    uuid.UUID
}

type Group struct {
	ID          uuid.UUID
	Name        string
	Description string
	AdminID     uuid.UUID
}

type GroupMember struct {
	UserID  uuid.UUID
	GroupID uuid.UUID
}

type User struct {
	ID         uuid.UUID
	Name       string
	Email      string
	IsVerified bool
	Password   string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
